### ISSUE TITLE
Make readme.md good looking.

### ISSUE THREAD

**Issue by Rupeshiya** [Rupeshiya/Random-Quote-Generator#2]

**Comment by cajuuh** [comment]
may i?

**Comment by Rupeshiya** [comment]
sure @cajuuh  go ahead.

**Comment by syauqiahmd** [comment]
may i help you with icon design ?

**Comment by Rupeshiya** [comment]
@syauqiahmd if you want you can add logo for this https://github.com/Rupeshiya/Random-Quote-Generator/issues/3
