### ISSUE TITLE
add logo for the web app

### ISSUE THREAD

**Issue by Rupeshiya** [Rupeshiya/Random-Quote-Generator#3]

**Comment by syauqiahmd** [comment]
ok, I get it
by the way.... nice to meet you i'm Syauqi from indonesia

**Comment by vincentt117** [comment]
Hi, for add logo, where were you looking to add it? Or were you looking for someone to create a logo for the site?

**Comment by Rupeshiya** [comment]
@vincentt117  I am talking about to create and add logo in readme.md for this web app.

**Comment by theranbrig** [comment]
I will take care of this if you want.

**Comment by buddhikac96** [comment]
i'm work on this issue
